version: '3'

services:

  postgres:
    image: 'postgres:14.0'
    container_name: chatapi-postgres
    user: postgres
    volumes:
      - chatapi-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - chatapi-external

volumes:
  chatapi-data:

networks:
  chatapi-external:
